import StoreProvider from "./StoreProvider";

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "react-tooltip/dist/react-tooltip.css";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import "/public/css/style.scss";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
